name: Publish to website.publish

"on":
  push:
    branches:
      - main

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Creates output folder and copy everything too it
        run:  |
              mkdir output
              rsync -av --exclude='output/' --exclude='.git/' / output/
      - name: Pushes to public repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
        env:
          SSH_DEPLOY_KEY: ${{ secrets.WORKFLOW_DEPLOY_KEY }}
        with:
          source-directory: 'output/'
          destination-github-username: 'niklasbuhl'
          destination-repository-name: 'website.publish'
          user-email: 'hello@niklasbuhl.com'
          commit-message: pushed from $GITHUB_REF
          target-branch: 'main'
