name: Publish to website.publish

"on":
  push:
    branches:
      - main

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Creates output folder and copy everything too it
        run:  |
              mkdir output
              ls
              rsync -av --exclude='output/' --exclude='.git/' ./ output/

